### ISSUE TITLE
CLI Extra spaces error

### ISSUE THREAD

**Issue by silviuburz** [mucs420f19/Hercules#76]
The CLI does not behave correctly when extra spaces are introduced in a command.

Example:
edit class name1 \double space\ name 2

produces unexpected results. This behavior needs to be handled.

**Comment by lawilli4** [comment]
Should take about 2 hours to implement a fix.

**Comment by lawilli4** [comment]
26 October: Worked from 5:00 to 5:20.

Took about 20 minutes to complete.
