### ISSUE TITLE
CLI Improper Text When Saving

### ISSUE THREAD

**Issue by lawilli4** [mucs420f19/Hercules#78]
When overwriting an existing save file from the REPL, the terminal displays text that an error has occurred even if successful. The save command behaves as expected, but displays incorrect text.

**Comment by silviuburz** [comment]
Estimated 1 hour to debug and implement a fix

**Comment by silviuburz** [comment]
Assigned back to Luke

**Comment by lawilli4** [comment]
4 November 2019: Worked on this issue from 2:30 to 2:35.

Took less than five minutes to fix.
