### ISSUE TITLE
Create a node(M)

### ISSUE THREAD

**Issue by Qpirons** [mucs420f19/Hercules#81]
Add the ability to create a node in the gui

**Comment by Qpirons** [comment]
Primary Quinn

**Comment by bmekstro** [comment]
Secondary Brian

**Comment by bmekstro** [comment]
Started work at 12pm with Quinn

**Comment by bmekstro** [comment]
Worked on this for 3 hours with Quinn.  Have a very basic version working that is just a rectangle, with no linking capabilities or information.

**Comment by Qpirons** [comment]
Worked with brain for another 2hrs. Have add class node, edit class node and delete class node in there as well
