### ISSUE TITLE
Off scene continuity (S)

### ISSUE THREAD

**Issue by Qpirons** [mucs420f19/Hercules#94]
Maintain class data when drug off screen.

**Comment by bmekstro** [comment]
Primary Brian

**Comment by bmekstro** [comment]
Started work at 12pm

**Comment by bmekstro** [comment]
Worked on this for roughly an hour.

**Comment by bmekstro** [comment]
Built in by default into the nuklear library.  Going to keep open for testing until GUI is completely finished.

**Comment by bmekstro** [comment]
Closing.  Only took an hour
