### ISSUE TITLE
Relationship lines move around classes (L)

### ISSUE THREAD

**Issue by Qpirons** [mucs420f19/Hercules#99]
When representing a relationship with an arrow, have the arrow go around existing classes.

**Comment by bmekstro** [comment]
Secondary Brian

**Comment by bmekstro** [comment]
This is an ongoing task that will not be closed in sprint 3.  Right now lines go underneath individual nodes.  Spent the bulk of time getting lines to draw directly to nodes before we could work on them going around nodes.

**Comment by lawilli4** [comment]
Used our group "no" for this requirement.
